src/Entity/Page.php
<?php

/*
 * This file is part of the Ipnoz Admin bundle.
 *
 * (c) David Dadon <david.dadon@ipnoz.net>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

declare(strict_types=1);

namespace Ipnoz\AdminBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Ipnoz\AdminBundle\Entity\Contracts;

/**
 * @author David Dadon <david.dadon@ipnoz.net>
 *
 * @ORM\MappedSuperclass()
 */
class Page implements Contracts\Referenceable, Contracts\Publishable
{
    use Contracts\IdTrait;
    use Contracts\ContentTrait;
    use Contracts\PermalinkTrait;
    use Contracts\ReferenceableTrait;
    use Contracts\PublishableTrait;

    /**
     * @var string
     * @ORM\Column(unique=true, nullable=true)
     */
    private $stringId;

    /**
     * @var string
     * @ORM\Column(type="string", nullable=true)
     */
    private $name;


    public function getStringId(): ?string
    {
        return $this->stringId;
    }

    public function setStringId(?string $stringId): void
    {
        $this->stringId = $stringId;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    public function getAnyName(): string
    {
        return $this->name ?: ($this->stringId ? 'id : '.$this->stringId : 'id : '.$this->id);
    }
}

src/Resources/views/Page/form.html.twig
{% extends '@IpnozAdmin/Base/form.html.twig' %}

{% use '@IpnozAdmin/Base/tabs.html.twig' %}

{% block tabs_menu %}
    {{ block('tabs_header') }}
{% endblock %}

{% block content %}
    {{ form_start(form) }}
        <div class="row">
            <div class="col-12 col-md-9">
                <section>
                    {{ block('tabs_content') }}
                </section>
            </div>
            <div class="col-md-3">
                {{ form_row(form.publish) }}
            </div>
        </div>
    {{ form_end(form) }}
{% endblock %}

{% block tabs_content_inner %}
    {% embed '@IpnozAdmin/Base/tabs-pane-content.html.twig' %}
        {% set tabPane = tabs.tab1 %}
        {% block tab_pane %}
            {{ form_row(form.name) }}
            {{ form_row(form.bodyHtml) }}
        {% endblock %}
    {% endembed %}
    {% embed '@IpnozAdmin/Base/tabs-pane-content.html.twig' %}
        {% set tabPane = tabs.tab2 %}
        {% block tab_pane %}
            {{ form_row(form.metas) }}
        {% endblock %}
    {% endembed %}
    {% embed '@IpnozAdmin/Base/tabs-pane-content.html.twig' %}
        {% set tabPane = tabs.tab3 %}
        {% block tab_pane %}
            {{ form_row(form.permalink) }}
            {{ form_row(form.createdAt) }}
        {% endblock %}
    {% endembed %}
{% endblock %}

src/Resources/views/Page/index.html.twig
{% extends '@IpnozAdmin/Base/Table/table.html.twig' %}

{% use '@IpnozAdmin/Base/Misc/link-buttons.html.twig' %}

{% set routeBase = 'ipnoz_admin_page_' %}

{% block admin_toolbar_content %}
    {% set link_button_route = routeBase ~'new' %}
    {% set link_button_title = 'Create a page' %}
    {{ block('link_button_new') }}
{% endblock %}

{% block table_thead %}
    <tr>
        <th>Name of the page</th>
        <th class="menu"></th>
    </tr>
{% endblock %}

{% block table_tbody %}
    {% for key, page in pages %}
    <tr class="{{ page.status }}">
        <td>
            {{ page.anyName }}
        </td>
        <td class="menu">
        {% embed '@IpnozAdmin/Base/Table/ActionMenu/base.html.twig' %}
            {% set modifyText = 'Modify the page' %}
            {% set modifyPath = path(routeBase ~'edit', { 'id': page.id }) %}
            {% set action_button_id = key %}
            {% set onlineStatusAction = path(routeBase ~'state', { 'id': page.id }) %}
            {% set isOnline = page.isOnline %}
            {% set deleteAction = path(routeBase ~'delete', { 'id': page.id }) %}
            {% set deleteActionName = page.getName() %}
        {% endembed %}
        </td>
    </tr>
    {% endfor %}
{% endblock %}

{% block modals %}
    {{ include ('@IpnozAdmin/Modals/delete-item.html.twig', {'modal_description': 'Supprimer la page <strong>%name%</strong> définitivement ?'}) }}
{% endblock %}